config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'
  
  get    '/signup',  to: 'users#new'
  get   '/new_user',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  post   '/attendance_time_create',   to: 'users#attendance_time'
  post   '/leaving_time_create',      to: 'users#leaving_time'
  post   '/update_basic_info',        to: 'users#update_basic_info'
  get    '/work_on_employee',         to: 'users#work_on_employee'
  
  post   '/attendance_update',        to: 'attendances#attendance_update'
  patch  '/one_overtime_apply',       to: 'attendances#one_overtime_apply'
  patch  '/one_overtime_approval',    to: 'attendances#one_overtime_approval'
  patch  '/attendance_edit_approval', to: 'attendances#attendance_edit_approval'
  patch  '/one_month_apply',          to: 'attendances#one_month_apply'
  patch  '/one_month_attendance_approval', to: 'attendances#one_month_attendance_approval'
  get    '/attendance_log',           to: 'attendances#attendance_log'
  get    '/log_search',               to: 'attendances#log_search'
  get    '/csv_output',               to: 'users#csv_output'
  post   '/csv_input',                to: 'users#csv_input'

  resources :users do
  member do
  get :following, :followers
   end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  # resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :attendances
  resources :bases do
    member do
      get   'edit_base_info'
      patch 'update_base_info'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # has_many :microposts, dependent: :destroy
  has_many :attendances, dependent: :destroy
  has_many :one_month_attendances
  #dependent: :destroy
  attr_accessor :remember_token, :activation_token, :reset_tokens
  before_create :create_activation_digest
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  has_secure_password
  validates :name,  presence: true, length: { maximum: 50 }
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true,confirmation: true
  validates :employee_number,  presence: true
  validates :designated_work_start_time,  presence: true
  validates :designated_work_end_time,  presence: true
  validates :basic_work_time,  presence: true
  
  require 'csv'
  
  def self.import(file)
    users = []
    #重複id
    overlap_id = []
    CSV.foreach(file.path, headers: true) do |row|

      if exists?(id: row["id"])
        overlap_id.push(row["id"])
        next
      end
      user = new(row.to_hash.slice(*updatable_attributes))
      
      if user.valid?
        users.push(user)
      else
        return "id#{row["id"]}のデータに不備があったため入力失敗しました"
      end
    end
    
    users.each do |user|
      if !user.save
        return "id#{user.id}のデータ保存時にエラーが発生しました"
      end
          # 重複したidがあればメッセージに表示
      return "アップデートが成功しました"
    end
  end

  # 更新を許可するカラムを定義
  def self.updatable_attributes
    ["id", "name", "email", "affiliation", "employee_number","uid",
     "basic_work_time", "designated_work_start_time", "designated_work_end_time", "superior",
     "password"]
  end
  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
    
  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

    # トークンがダイジェストと一致したらtrueを返す
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  # アカウントを有効にする
  def activate
    update_columns(activated: true, activated_at: Time.zone.now)
  end

  # 有効化用のメールを送信する
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end
  
   # パスワード再設定の属性を設定する
  def create_reset_digest
    self.reset_token = User.new_token
    update_columns(reset_digest: User.digest(reset_token), reset_sent_at: Time.zone.now)
  end
  
    # パスワード再設定のメールを送信する
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end
  
  # パスワード再設定の期限が切れている場合はtrueを返す
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end
  
  # 試作feedの定義
  # 完全な実装は次章の「ユーザーをフォローする」を参照
  def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE follower_id = :user_id"
    Micropost.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
  end
  
    # ユーザーをフォローする
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

  
  private
  # 有効化トークンとダイジェストを作成および代入する
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
before_action :correct_user,   only: [:edit, :update]
before_action :admin_user,     only: [:destroy, :edit_basic_info]
 
 include UsersHelper
 require 'csv'
  
  def index
    id = cookies[:user_id]
    @user = User.find(id)
    if current_user.admin && @user.admin
     @users = User.paginate(page: params[:page])
    else
     flash[:warning] = "他ユーザーを閲覧することはできません。"
     redirect_to login_url
    end
  end

 def show
    #管理者ユーザーは取得できない

    #ユーザー情報を取得
    @user = User.find(params[:id])
    id = cookies[:user_id]
    @user_confirm = User.find(id)
    if @user_confirm.admin? || @user.admin
      if @user != @user_confirm
        flash[:warning] = "他ユーザーを閲覧することはできません。"
        redirect_to current_user
      end
    else
      #管理者でなければ、勤怠情報を確認することができる。
      if (current_user.superior == true || current_user.id == @user.id) && (!@user_confirm.admin? || !@user.admin?)
        #表示用上長ユーザー情報を取得
        @superior_user = User.where(superior: true).where.not(id: current_user.id)
        #セレクトボックス用上長ユーザー情報
        @superior = User.where(superior: true)
        #上長に対する残業申請の有無
        @overtime_to_sp = Attendance.where(authority_user_id: @user.id, apply_state: 2)
        @overtime_apply = @overtime_to_sp.includes(:user)
        @overtime_applys = @overtime_apply.group_by{|i| i.user.id}
        #上長に対する勤怠変更申請の有無
        @attendance_change_to_sp = Attendance.where(edit_authority_user_id: @user.id, attendance_change_state: 2)
        @attendance_change =  @attendance_change_to_sp.includes(:user)
        #上長に対する勤怠変更申請の有無
        @attendance_change_applys = @attendance_change.group_by{|i| i.user.id}
        #１ヶ月勤怠申請の有無
        @one_month_edit_to_sp = OneMonthAttendance.where(one_month_authority_user_id: @user.id, one_month_apply_state: 2).order('one_month_apply_date')
        #@one_month_edit = @one_month_edit_to_sp.includes(:user)
        @one_month_applys = @one_month_edit_to_sp.group_by{|i| i.one_month_applying_user_id}
       
        if params[:first_day] == nil
          # params[:first_day]が存在しない(つまりデフォルト時) # ▼月初(今月の1日, 00:00:00)を取得します
          @first_day = Date.today.beginning_of_month
        else
          @first_day = params[:first_day].to_date
        end
        @last_day = @first_day.end_of_month
        #上長に対する１か月勤怠の申請の有無
        @one_month_apply = OneMonthAttendance.find_by(one_month_applying_user_id: @user.id,one_month_apply_date: @first_day)
        if !@one_month_apply.nil?
          @one_month_appled_user = User.find_by(id: @one_month_apply.one_month_authority_user_id)
        end
        #曜日表示用に使用する
        @youbi = %w(日 月 火 水 木 金 土)
        #今月の初日から最終日の期間分を取得 
        (@first_day..@last_day).each do |days|
          #ない日付はインスタンスを生成して保存する
          if not @user.attendances.any? { |obj| obj.day == days }
            dates = Attendance.new(user_id: @user.id, day: days)
            dates.save
          end
        end 
        #当月を昇順で取得し@daysへ代入
        @days = @user.attendances.where('day >= ? and day <= ?', @first_day, @last_day).order('day')
        #出勤日数表示
        @attendance_sum = @days.where.not(attendance_time: nil, leaving_time: nil).count
        #在社時間表示
        second = 0
        next_second = 0
        @total_time = 0
        @days.each do |d|
          if d.attendance_time.present? && d.leaving_time.present?
            if d.edit_next_check == 0
              second = second + times(d.attendance_time,d.leaving_time)
              @total_time = @total_time + second.to_i
            end
            if d.edit_next_check == 1
              next_second = next_second + next_times(d.attendance_time,d.leaving_time)
              @total_time = @total_time + next_second.to_i
            end
          end
        end
      #superior以外は他ユーザー情報を見れない。
      else 
        flash[:warning] = "他ユーザーの情報を閲覧することができません！"
        redirect_to current_user
      end
    end
  end
  
  #出社時間
  def attendance_time
    @user = User.find(params[:id])
    @attendance_time = @user.attendances.find_by(day: Date.current)
    @attendance_time.update_attributes(attendance_time: current_time,
                                       before_edit_attendance_time: current_time)
    flash[:info] = "出社登録完了しました！！"
    redirect_to @user
  end
  
  #退社時間
  def leaving_time
    @user = User.find(params[:id])
    @leaving_time = @user.attendances.find_by(day: Date.current)
    @leaving_time.update_attributes(leaving_time: current_time,
                                     before_edit_leaving_time: current_time)
    flash[:info] = "退社登録完了しました！！"
    redirect_to @user
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
       cookies[:user_id] = @user.id
       log_in @user
       redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "ユーザー情報を削除しました！！"
    redirect_to s_path
  end
  
  def update
    if @user.update_attributes(user_params)
      # 更新に成功した場合を扱う。
      flash[:success] = "アカウントを更新しました"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def edit_basic_info
    if params[:id].nil?
      @user  = User.find(current_user.id)
    else
      @user  = User.find(params[:id])
    end
  end
  
  def update_basic_info
      @user = User.find(params[:id])
    if @user.update_attributes(users_basic_params)
        # binding.pry
      # 更新に成功した場合を扱う。
      flash[:success] = "基本情報を修正しました！！"
      id = cookies[:user_id]
      @user = User.find(id)
      redirect_to @user
    else
      render 'index'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "ユーザーを削除しました！！"
    redirect_to users_url
  end
  
  def csv_output
    @user = User.find(params[:id])
    date = params[:first_day].to_datetime
    output_first_day = date.beginning_of_month
    output_last_day = output_first_day.end_of_month
    @youbi = %w(日 月 火 水 木 金 土)
    
    @attendances = @user.attendances.where(day: output_first_day..output_last_day).order('day')
    respond_to do |format|
      format.csv do
        send_data render_to_string, filename: "#{@user.name}.csv", type: :csv
      end
    end
  end
  
  def csv_input
    # fileはtmpに自動で一時保存される
    if !params[:file].blank?
      # 保存と結果のメッセージを取得して表示
      message = User.import(params[:file])
      if message == []
        flash[:notice] = "インポートするユーザが存在しません。"
      elsif message.present?
        flash[:notice] = message
      end
    else
      flash[:error] = "読み込むCSVファイルをセットしてください"
    end
    redirect_to users_path
  end
  
  def work_on_employee
    id = cookies[:user_id]
    @user = User.find(id)
    if current_user.admin && @user.admin
      @work_on_list = Attendance.where(day: Date.today, leaving_time: nil).where.not(attendance_time: nil).order(user_id: "ASC")
    else
     flash[:warning] = "他ユーザーを閲覧することはできません。"
     redirect_to login_url
    end
  end

  private
    def user_params
      params.require(:user).permit(:name,:email,:uid ,:employee_number ,:password,
                                   :password_confirmation,:affiliation,
                                   :designated_work_start_time,:designated_work_end_time ,:basic_work_time)
    end
    
    def users_basic_params
      params.require(:user).permit(:name,:email,:uid ,:employee_number ,:password,:password_confirmation,
                                   :affiliation,:designated_work_start_time,:designated_work_end_time ,:basic_work_time)
    end
                
    # beforeアクション

     # 正しいユーザーかどうか確認
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
    
    # 管理者かどうか確認
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
  
  
  #在社時間計上用
  def working_times(a,b)
    attendancetime = Time.mktime(a.year, a.month, a.day, a.hour, a.min, 0, 0)
    leavingtime = Time.mktime(b.year, b.month, b.day, b.hour, b.min, 0, 0)
    (((leavingtime - attendancetime) / 60) / 60).truncate(2)
  end
  
  def additional_working_times(a,b)
    attendancetime = Time.mktime(a.year, a.month, a.day, a.hour, a.min, 0, 0)
    leavingtime = Time.mktime(b.year, b.month, b.day, b.hour, b.min, 0, 0)
    ((((leavingtime + 1.day) - attendancetime) / 60) / 60).truncate(2)
  end
     # 引数の時刻データの秒を０にして差を求める
  def times(x,y)
    c = Time.mktime(x.year, x.month, x.day, x.hour, x.min, 0, 0)
    d = Time.mktime(y.year, y.month, y.day, y.hour, y.min, 0, 0)
    (d - c).to_i
  end
  #翌日用
  def next_times(x,y)
    c = Time.mktime(x.year, x.month, x.day, x.hour, x.min, 0, 0)
    d = Time.mktime(y.year, y.month, y.day, y.hour, y.min, 0, 0)
    ((d + 1.day) - c).to_i
  end
  
  def total_attendance_times(t)
    format("%.2f", ((t.hour * 60.0) + t.min)/60) if t.present?
  end
  
  def basic_info_times(t)
    format("%.2f", ((t.hour * 60.0) + t.min)/60) if t.present?
  end
  
  def current_time
    Time.new(
      Time.now.year,
      Time.now.month,
      Time.now.day,
      Time.now.hour,
      Time.now.min, 0
    )
  end

  # 引数で与えられたユーザーのGravatar画像を返す
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_attendance_edit_modal.html.erb
<!--モーダル表示勤怠変更承認-->
<div id ="inline-edit-popups">
 <% if @attendance_change_to_sp.blank? %>
  <div id= "aaa">【勤怠変更申請のお知らせはありません】</div>
 <% else %>
  <a id= "aaa" href="#attendance-edit-approval-modal" class="information">【勤怠変更申請のお知らせ】：</a><span class="notification"><%= "#{@attendance_change_to_sp.count}件の通知があります" %></span></p>
 <% end %>
</div>

<div class ="white-popup mfp-with-anim mfp-hide" id = "attendance-edit-approval-modal">
 <%= form_with model: @user, url: attendance_edit_approval_path, local: true do |f| %>
 <% @attendance_change_applys.each do |user_id, attendances| %>
  <% user = User.find(user_id) %>
	 <h4 class="title-modal">【<%= user.name %>からの勤怠変更申請】</h4>
   <table class = "table attendance-table table-striped table-bordered">
    <thead>
     <!--１列目-->
     <tr>
      <th rowspan = "3">日付</th>
      <th rowspan = "3">曜日</th>
      <th colspan = "4">変更前</th>
      <th colspan = "4">変更後</th>
      <th rowspan = "3">備考</th>
      <th rowspan = "3">指示者確認㊞</th>
      <th rowspan = "3">変更</th>
      <th rowspan = "3">勤怠を確認する</th>
     </tr>
     <!--2列目-->
     <tr>
      <th colspan = "2">出社</th>
      <th colspan = "2">退社</th>
      <th colspan = "2">出社</th>
      <th colspan = "2">退社</th>
     </tr>
     <!--3列目-->
     <tr>
      <th>時</th>
      <th>分</th>
      <th>時</th>
      <th>分</th>
      <th>時</th>
      <th>分</th>
      <th>時</th>
      <th>分</th>
     </tr>
    </thead>
    <% attendances.each do |attendance| %>
    <%= fields_for "attendances[]", attendance do |af| %>
    <tbody>
      <tr>
      <!--1行目：日付（日）-->
       <td><%= attendance.day.month %>/<%=attendance.day.day %></td>
      <!--2行目：日付（曜日）-->      
       <td><%= @youbi[attendance.day.wday] %></td>
      <!--3行目-4行目：出社変更前----空の場合-->
       <% if attendance.attendance_time.nil? %>
        <td></td>
        <td></td>
       <% else %>
        <td><%= attendance.attendance_time.to_s(:hour) %></td>
        <td><%= attendance.attendance_time.to_s(:min) %></td>
       <% end %>
       <!--5行目-6行目：退社変更前----空の場合-->
       <% if attendance.leaving_time.nil? %>
        <td></td>
        <td></td>
       <% else %>
        <td><%= attendance.leaving_time.to_s(:hour) %></td>
        <td><%= attendance.leaving_time.to_s(:min) %></td>
       <% end %>
      <!--7行目：変更後出社時間（hour）-->
       <td><%= attendance.edit_attendance_time.to_s(:hour) %></td>
　　　<!--8行目：変更後出社時間（min）-->
       <td><%= attendance.edit_attendance_time.to_s(:min) %></td>
      <!--9行目：変更後退社時間（hour）-->
       <td><%= attendance.edit_leaving_time.to_s(:hour) %></td>
　　　<!--10行目：変更後退社時間（min）-->
       <td><%= attendance.edit_leaving_time.to_s(:min) %></td>
      <!--11行目：備考欄-->
       <td><%= attendance.remarks %></td>
      <!--12行目：申請状況-->
       <td><%= af.select :attendance_change_state, Attendance.localed_attendance_change_state, {}, class: 'form-control'  %></td>
      <!--13行目：変更するか否か-->
       <td><%= af.check_box :change_flg, {}, true, false %></td>
      <!--14行目：勤怠確認-->
       <td><%= link_to '確認', user_path(id: user_id, first_day: @first_day), class: "btn btn-primary", :target => "_blank" %></td>
      </tr>
     </tbody>
     <% end %>
    <% end %>		
   </table>
 <% end %>
 <%= f.submit "登録", class: "btn btn-primary" %>
 <% end %>
</div>

<script>
 jQuery('#inline-edit-popups').magnificPopup({
    delegate: 'a'
    // removalDelay: 500
    // callbacks: {
    //   beforeOpen: function() {
    //      this.st.mainClass = this.st.el.attr('data-effect');
    //   },
    // },
});
</script>

app/views/users/_basic_info.html.erb
<%= form_for(@user, url: update_basic_info_path, method: :post) do |f| %>
 <%= hidden_field_tag :id, @user.id %>
  <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :指定勤務時間 %>
      <%= f.time_field :designated_work_start_time, class: 'form-control' %>

      <%= f.label :基本勤務時間 %>
      <%= f.time_field :basic_work_time, class: 'form-control'%>
      
      <%= f.submit "更新", class: "btn btn-primary" %>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user, url: yield(:url)) do |f| %>  
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :社員番号 %>
  <%= f.text_field :employee_number, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_one_month_apply_modal.html.erb
<!--モーダル表示勤怠承認-->
<div id ="attendance-popups">
 <% if @one_month_edit_to_sp.blank? %>
  <div id= "one_month_apply">【所属長承認申請のお知らせはありません】</div>
 <% else %>
  <a id= "one_month_apply" href="#one-month-apply-modal" class="information">【所属長承認申請のお知らせ】：</a><span class="notification"><%= "#{@one_month_edit_to_sp.count}件の通知があります" %></span><br>
 <% end %>
</div>

<div class ="white-popup mfp-with-anim mfp-hide" id = "one-month-apply-modal">
 <%= form_with model: @user, url: one_month_attendance_approval_path, local: true do |f| %>
 <% @one_month_applys.each do |user_id, attendances| %>
  <% user = User.find(user_id) %>
	 <h4 class="title-modal">【<%= user.name %>からの１ヶ月勤怠申請】</h4>
   <table class = "table attendance-table table-striped table-bordered">
    <thead>
     <tr>
      <th>申請月</th>
      <th>指示者確認㊞</th>
      <th>変更</th>
      <th>勤怠を確認する</th>
     </tr>
    </thead>
    <% attendances.each do |attendance| %>
    <%= fields_for "one_month_attendances[]", attendance do |af| %>
    <tbody>
      <tr>
      <!--1行目：日付（月）-->
       <td><%= attendance.one_month_apply_date.year %>年<%= attendance.one_month_apply_date.month %>月</td>
      <!--2行目：指示者確認-->
       <td><%= af.select :one_month_apply_state, OneMonthAttendance.localed_apply_state, {}, class: 'form-control'  %></td>
      <!--3行目：変更するか否か-->
       <td>
         <%= af.check_box :approval_flg, {}, true, false %>
       </td>
      <!--4行目：勤怠確認-->
       <td><%= link_to '確認', user_path(id: user_id, first_day: @first_day), class: "btn btn-primary", :target => "_blank" %></td>
      </tr>
     </tbody>
     <% end %>
    <% end %>		
   </table>
 <% end %>
 <%= f.submit "変更を送信する", class: "btn btn-primary" %>
 <% end %>
</div>

<script>
 jQuery('#attendance-popups').magnificPopup({
    delegate: 'a'
    // callbacks: {
    //   beforeOpen: function() {
    //      this.st.mainClass = this.st.el.attr('data-effect');
    //   },
    // },
});
</script>

app/views/users/edit.html.erb
<% provide(:title, "アカウント情報の更新") %>
<h1>アカウント情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      
      <%= f.label :所属 %>
      <%= f.text_field :affiliation, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "パスワード確認" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "更新", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, "ユーザー一覧") %>
<h1>ユーザー一覧</h1>

<div class="search-content">
  <%= form_tag csv_input_path, method: :post, multipart: true do |f| %>
    <div class="search_item">
      <%= text_field_tag 'filename',"", id: "filename", disabled: true %>
      <%= file_field_tag 'file', id: "file_input", style: "display: none;", onchange: "file_selected($(this));" %>
      <%= button_tag 'ファイル選択', class: %i(btn-primary csv_input_btn), type: 'button', onclick: "$('#file_input').click();" %>
    </div>
      <%= submit_tag "インポート", class: "btn btn-primary" %>
  <% end %>
</div>


<%= will_paginate %>

<ul class="users">
  <% @users.each do |user| %>
   <div class="accordion">
    <h4><%= user.name %></h4>
    <% if !user.admin? %>
      |&emsp;<%= link_to "削除", user_path(user), method: :delete, data: {confirm: "削除してよろしいですか？"}, class: "btn btn-primary" %><br>
    <% end %>
      
    <button type="button" class="ac<%= user.id %> btn btn-primary btn-sm user-info">編集</button>
    　<%= form_for(user, url: update_basic_info_path, method: :post) do |f| %>
      <%= hidden_field_tag :id, user.id %>
      <%= render 'shared/error_messages', object: f.object %>
       <%= f.label :氏名 %>
       <%= f.text_field :name, class: 'form-control' %>
      
       <%= f.label :メールアドレス %>
       <%= f.text_field :email, class: 'form-control' %>
       
       <%= f.label :所属 %>
       <%= f.text_field :affiliation, class: 'form-control' %>
      
       <%= f.label :社員番号 %>
       <%= f.text_field :employee_number, class: 'form-control' %>
       
       <%= f.label :カードID %>
       <%= f.text_field :uid, class: 'form-control' %>
      
     　<%= f.label :パスワード %>
       <%= f.password_field :password, class: 'form-control' %>
       
       <%= f.label :パスワード確認 %>
       <%= f.password_field :password_confirmation, class: 'form-control' %>
       
       <% if !user.admin? %>
   　     <%= f.label :基本勤務時間 %>
         <%= f.time_field :basic_work_time, class: 'form-control' %>

         <%= f.label :指定勤務開始時間 %>
         <%= f.time_field :designated_work_start_time, class: 'form-control'%>
      
         <%= f.label :指定勤務終了時間 %>
         <%= f.time_field :designated_work_end_time, class: 'form-control'%>
       <% end %>

       <%= f.submit "更新", class: "btn btn-primary btn-bg" %>
      <% end %>
   </div>
  <% end %>
</ul>

<%= will_paginate %>

<script>
  $('.accordion button').click(function(){
      $(this).next('form').slideToggle();
  });
  
  function file_selected(file_field){
    var filename = $(file_field)[0].files[0].name;
    $("#filename").val(filename);
  }
    
</script>