config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'
  
  get    '/signup',  to: 'users#new'
  get   '/new_user',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  post   '/attendance_time_create',   to: 'users#attendance_time'
  post   '/leaving_time_create',      to: 'users#leaving_time'
  post   '/update_basic_info',        to: 'users#update_basic_info'
  get    '/work_on_employee',         to: 'users#work_on_employee'
  
  post   '/attendance_update',        to: 'attendances#attendance_update'
  patch  '/one_overtime_apply',       to: 'attendances#one_overtime_apply'
  patch  '/one_overtime_approval',    to: 'attendances#one_overtime_approval'
  patch  '/attendance_edit_approval', to: 'attendances#attendance_edit_approval'
  patch  '/one_month_apply',          to: 'attendances#one_month_apply'
  patch  '/one_month_attendance_approval', to: 'attendances#one_month_attendance_approval'
  get    '/attendance_log',           to: 'attendances#attendance_log'
  get    '/log_search',               to: 'attendances#log_search'
  get    '/csv_output',               to: 'users#csv_output'
  post   '/csv_input',                to: 'users#csv_input'

  resources :users do
  member do
  get :following, :followers
   end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  # resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :attendances
  resources :bases do
    member do
      get   'edit_base_info'
      patch 'update_base_info'
    end
  end
end

app/views/layouts/_header.html.erb
<% if current_user?(@user) %>
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
   <%= link_to "勤怠管理システム", current_user, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
         <li><%= link_to "トップへ", current_user %></li>
        <% if logged_in? %>  
        <% if current_user.admin == true %>
          <li><%= link_to "ユーザー一覧", users_path(id: @user.id) %></li>
          <li><%= link_to "出勤社員一覧", work_on_employee_path(params:{id: @user.id}) %></li>
          <li><%= link_to "拠点情報の修正", bases_path(params:{id: @user.id}) %></li>
          <li><%= link_to "基本情報の修正", "#" %></li>
        <% end %>
        
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
              アカウント <b class="caret"></b>
            </a>
            
            
            <ul class="dropdown-menu">
            <%# if !admin?(@user) %>
              <%# link_to "勤怠表示画面", current_user %>
            <%# end %>
              <li><%#= link_to "個人情報編集画面", edit_user_path(current_user)  %></li>

              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>
<% end %>

app/views/layouts/_rails_default.html.erb
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
        <% flash.each do |message_type, message| %>
         <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>